// 12-Vue/vue-bases/src/components/CustomForm.vue
<template>
<form @submit.prevent="handleSubmit" class="max-w-sm mx-auto text-start" novalidate autocomplete="off">
  <div class="mb-5">
    <label for="name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white text-start">Your name</label>
    <input v-model="formData.name" type="text" id="name" name="name" :class="{ '!border-red-500': formError.name === '' ? false : true }" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" />
    <p class="mt-2 text-sm text-red-600 dark:text-red-500" v-if="formError.name === '' ? false : true">{{ formError.name }}</p>
</div>
  <div class="mb-5">
    <label for="tel" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white text-start">Your phone</label>
    <input v-model="formData.phone" type="text" id="tel" name="tel" :class="{ '!border-red-500': formError.phone === '' ? false : true }"  class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" />
    <p class="mt-2 text-sm text-red-600 dark:text-red-500" v-if="formError.phone === '' ? false : true">{{ formError.phone }}</p>
  </div>
  <div class="flex items-start mb-5">
    <div class="flex items-center h-5">
      <input v-model="formData.remember" id="remember" type="checkbox" name="remember" class="w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-blue-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800" />
    </div>
    <label for="remember" class="ms-2 text-sm font-medium text-gray-900 dark:text-gray-300">Remember me</label>
  </div>

  <button
    :disabled="isLoading" 
    type="submit" 
    class="!w-full text-white disabled:opacity-60 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
  >
    {{ textButton }}
  </button>

  <pre>
    {{ JSON.stringify(formData) }}
  </pre>
</form>
</template>

<script>
export default {
    data(){
        return {
            isLoading: false,
            textButton: 'Enviar',
            formData: {
                name: "",
                phone: "",
                remember: false
            },
            formError: {
                name: "",
                phone: ""
            }
        }
    }, 
    methods: {
        async handleSubmit(e){

            // const formData = new FormData(e.target);
            
            // let data = Object.fromEntries(formData);
        
            // data = {
            //     ...data,
            //     remember: data.remember === undefined ?  false : true
            // }

            // const data = {
            //     name: this.$refs.inputName.value,
            //     phome: this.$refs.inputPhone.value,
            //     remember: this.$refs.inputCheck.checked,
            // }

            const data = { ...this.formData };


            if(data.name === ''){
                this.formError.name = "El nombre está vacio"
            }
            
            if(data.phone === ''){
                this.formError.phone = "El teléfono está vacio"
            }

            if(this.formData.name === '' || this.formData.phone === ""){
                return;
            }

            // if(data.name === '' || data.phone === ''){
            //     alert("Los datos son necesarios");
            //     return;
            // }

            this.isLoading = true;

            const result = await fetch('https://jsonplaceholder.typicode.com/users', {
                method: 'POST',
                headers: {
                    'Content-type': 'application/json',
                },
                body: JSON.stringify(data)
            }).then(res => res.json());

            this.isLoading = false;

            this.formError.name = "";
            this.formError.phone = "";

            console.log(result)
        }
    },
    computed: {
        btnText(){
            return this.isLoading == true ? "Cargando..." : "Enviar";
        }
    },
    watch: {
        isLoading(newValue){
            if(newValue === true){
                this.textButton = 'Cargando...';
            } else {
                this.textButton = 'Enviar';
            }
        }
    }
}
</script>

// 11-React/react-inicios/src/components/CustomForm.jsx
import { useState } from 'react'

export const CustomForm = () => {
    const [error, setError] = useState(false) // setError
    const [ inputValues, setInputValues ] = useState({
        nombre: "",
        apellido: "",
        email: ""
    })


    //const inputs = useRef([]);

    const handleSubmit = (e) => {
        e.preventDefault();

        // Con useRef([])
        //if(inputs.current.length === 0) throw new Error("No existen elementos");

        // const [ nombre, apellido, correo ] = inputs.current.map(input => input.value);

        // if(nombre.length === 0){
        //     setError(true);
        //     return;
        // }

        // console.log({ nombre, apellido, correo })
        //setError(false)


        // Con FormData
        //const users = Object.fromEntries(new FormData(e.target));

        // const users = {
        //     nombre: fields.get("nombre"),
        //     apellido: fields.get("apellido"),
        //     correo: fields.get("email")
        // }

        // if(users.nombre.length === 0){
        //     setError(true);
        //     return;
        // }

        // console.log(users)
        // setError(false)


        // Con useState()
        if(inputValues.nombre.length === 0){
            setError(true);
            return;
        }

        console.log(inputValues)
        setError(false)

        // enviar la información a un api rest
    }

    const handleChange = (e) => {
        setInputValues({
            ...inputValues,
            [e.target.name]: e.target.value, // == nombre: e.target.value,
        })
    }

    return (
        <form onSubmit={handleSubmit} className="max-w-sm mx-auto" autoComplete="off">
            <p> Nombre: { inputValues.nombre } | Apellido: {inputValues.apellido} | Email: { inputValues.email } </p>
            <div className="mb-5">
                <label
                    htmlFor="nombre"
                    className={`block mb-2 text-sm font-medium text-gray-900`}
                >
                    Nombre
                </label>
                <input
                    // ref={(element) => inputs.current[0] = element}
                    type="text"
                    id="nombre"
                    name="nombre"
                    className={`shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 ${error === true ? "border-red-400" : ""}`}
                    placeholder="Fulanito..."
                    value={inputValues.nombre}
                    onChange={handleChange}
                />
            </div>
            <div className="mb-5">
                <label
                    htmlFor="apellido"
                    className="block mb-2 text-sm font-medium text-gray-900"
                >
                    Apellido
                </label>
                <input
                    // ref={(element) => inputs.current[1] = element}
                    type="text"
                    id="apellido"
                    name="apellido"
                    className="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
                    placeholder="Del Rio..."
                    value={inputValues.apellido}
                    onChange={handleChange}
                />
            </div>
            <div className="mb-5">
                <label
                    htmlFor="email"
                    className="block mb-2 text-sm font-medium text-gray-900"
                >
                    Correo electrónico
                </label>
                <input
                    // ref={(element) => inputs.current[2] = element}
                    type="email"                    
                    id="email"
                    name="email"
                    className="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
                    placeholder="fulanito@gmail.com"
                    value={inputValues.email}
                    onChange={handleChange}
                />
            </div>
            <div className="flex items-start mb-5">
                <div className="flex items-center h-5">
                    <input
                        id="terms"
                        type="checkbox"
                        defaultValue=""
                        className="w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-blue-300"
                        required=""
                    />
                </div>
                <label
                    htmlFor="terms"
                    className="ms-2 text-sm font-medium text-gray-900"
                >
                    Estoy de acuerdo con los{" "}
                    <a href="#" className="text-blue-600 hover:underline">
                        terminos y condiciones
                    </a>
                </label>
            </div>
            <button
                type="submit"
                className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center"
            >
                Agregar usuario
            </button>
        </form>
    )
}
